[providers.go]
path = "backend"

[providers.node]
path = "frontend"

[build]
cmds = [
  "cd backend && go build -o app cmd/main.go",
  "cd frontend && npm install && npm run build"
]

[start]
cmd = "cd backend && PORT=$PORT ./app"
